# Generated by Django 2.2.4 on 2019-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pontoturistico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='atracoes', to='atracoes.Atracao'),
        ),
    ]
